apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.10
    profile: false

    max_hamming: 0

    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    tag:
      ids: [0, 1, 2, 3, 4, 5]
      frames: ["tag_0", "tag_1", "tag_2", "tag_3", "tag_4", "tag_5"]
      sizes: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10]