/**:
  ros__parameters:
    family: "36h11"

    # Tag edge size in meters.
    # 10 cm x 10 cm tag = 0.10 m edge length.
    size: 0.10

    max_hamming: 0
    profile: false

    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    tag:
      ids: [0, 1, 2, 3, 4, 5]
      frames: ["tag_0", "tag_1", "tag_2", "tag_3", "tag_4", "tag_5"]
      sizes: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10]