/**:
  ros__parameters:
    family: "36h11"

    # Actual detectable AprilTag edge, excluding the outer white margin.
    size: 0.20

    max_hamming: 0
    profile: false

    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    tag:
      ids: [0, 1, 2, 3, 4, 5]
      frames: ["tag_0", "tag_1", "tag_2", "tag_3", "tag_4", "tag_5"]
      sizes: [0.20, 0.20, 0.20, 0.20, 0.20, 0.20]